name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: setup jdk ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew build
    - name: Upload to Modrinth
      uses: RubixDev/modrinth-upload@v1
      with:
        token: ${{ secrets.MODRITH }}
        file_path: ./build/libs/weapons-collection-0.1.jar
        name: 0.1
        version: 0.1
        relations: P7dR8mSH:required
        game_versions: 1.20.1
        release_type: alpha
        loaders: fabric
        featured: false
        project_id: e6VuC4iy
