name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: '0.1'

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: setup jdk ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: build
      run: ./gradlew build -Pversion=${{ github.event.inputs.version }}
    - name: Find build artifact
      id: find_artifact
      run: |
        artifact=$(find build/libs -type f -name 'weapons-collection-*.jar' | head -n 1)
        echo "artifact_name=$(basename $artifact)" >> $GITHUB_ENV
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/libs
        asset_name: ${{ env.artifact_name }}
        asset_content_type: application/java-archive
    - name: Upload to Modrinth
      uses: RubixDev/modrinth-upload@v1
      with:
        token: ${{ secrets.MODRITH }}
        file_path: ./build/libs/${{ env.artifact_name }}
        name: 0.1
        version: 0.1
        relations: P7dR8mSH:required
        game_versions: 1.20.1
        release_type: alpha
        loaders: fabric
        featured: false
        project_id: e6VuC4iy
